name: Sync and Push to Playlist Repo

on:
  schedule:
    - cron: '30 1 * * *'  # Runs at 7:00 AM IST (1:30 AM UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git identity
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Clone your target repo (Dhruv0045/Playlist)
      run: |
        git clone https://x-access-token:${{ secrets.PAT_DHRUV0045 }}@github.com/Dhruv0045/Playlist.git
        cd Playlist

    - name: Download jtv.m3u from alex4528/m3u
      run: |
        curl -L https://raw.githubusercontent.com/alex4528/m3u/main/jtv.m3u -o Playlist/jiotv.m3u

    - name: Commit & push if jiotv.m3u has changed
      working-directory: Playlist
      run: |
        if [ -n "$(git status --porcelain jiotv.m3u)" ]; then
          git add jiotv.m3u
          git commit -m "🔄 Auto-update jiotv.m3u from alex4528/m3u"
          git push https://x-access-token:${{ secrets.PAT_DHRUV0045 }}@github.com/Dhruv0045/Playlist.git HEAD:main
        else
          echo "✅ No changes to commit."
        fi
